apiVersion: apps/v1
kind: Deployment
metadata:
  name: coincidencias-deployment
  labels:
    app: ms-coincidencias
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-coincidencias
  template:
    metadata:
      labels:
        app: ms-coincidencias
    spec:
      containers:
      - name: ms-coincidencias
        image: 085985863834.dkr.ecr.us-east-1.amazonaws.com/ms-coincidencias:${IMAGE_TAG}
        ports:
        - containerPort: 8084
        env:
        - name: DB_URL
          value: "jdbc:postgresql://sanosdb-service:5432/db_mascotas"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: db-password
        - name: EUREKA_URL
          value: "http://eureka-service:8761/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: coincidencias-service
spec:
  type: ClusterIP
  selector:
    app: ms-coincidencias
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084